/**
 * Country + demonym pairs for the passenger form selects: nationality shows
 * the demonym ("Filipino"), passport country of issue shows the country name.
 * Philippines leads (home market); the rest are alphabetical.
 */
export const COUNTRIES: { country: string; nationality: string }[] = [
  { country: 'Philippines', nationality: 'Filipino' },
  { country: 'Australia', nationality: 'Australian' },
  { country: 'Austria', nationality: 'Austrian' },
  { country: 'Bahrain', nationality: 'Bahraini' },
  { country: 'Bangladesh', nationality: 'Bangladeshi' },
  { country: 'Belgium', nationality: 'Belgian' },
  { country: 'Brazil', nationality: 'Brazilian' },
  { country: 'Brunei', nationality: 'Bruneian' },
  { country: 'Cambodia', nationality: 'Cambodian' },
  { country: 'Canada', nationality: 'Canadian' },
  { country: 'China', nationality: 'Chinese' },
  { country: 'Denmark', nationality: 'Danish' },
  { country: 'Egypt', nationality: 'Egyptian' },
  { country: 'Finland', nationality: 'Finnish' },
  { country: 'France', nationality: 'French' },
  { country: 'Germany', nationality: 'German' },
  { country: 'Greece', nationality: 'Greek' },
  { country: 'Hong Kong', nationality: 'Hong Konger' },
  { country: 'India', nationality: 'Indian' },
  { country: 'Indonesia', nationality: 'Indonesian' },
  { country: 'Ireland', nationality: 'Irish' },
  { country: 'Israel', nationality: 'Israeli' },
  { country: 'Italy', nationality: 'Italian' },
  { country: 'Japan', nationality: 'Japanese' },
  { country: 'Jordan', nationality: 'Jordanian' },
  { country: 'Kuwait', nationality: 'Kuwaiti' },
  { country: 'Laos', nationality: 'Lao' },
  { country: 'Malaysia', nationality: 'Malaysian' },
  { country: 'Mexico', nationality: 'Mexican' },
  { country: 'Myanmar', nationality: 'Burmese' },
  { country: 'Nepal', nationality: 'Nepalese' },
  { country: 'Netherlands', nationality: 'Dutch' },
  { country: 'New Zealand', nationality: 'New Zealander' },
  { country: 'Nigeria', nationality: 'Nigerian' },
  { country: 'Norway', nationality: 'Norwegian' },
  { country: 'Oman', nationality: 'Omani' },
  { country: 'Pakistan', nationality: 'Pakistani' },
  { country: 'Papua New Guinea', nationality: 'Papua New Guinean' },
  { country: 'Poland', nationality: 'Polish' },
  { country: 'Portugal', nationality: 'Portuguese' },
  { country: 'Qatar', nationality: 'Qatari' },
  { country: 'Russia', nationality: 'Russian' },
  { country: 'Saudi Arabia', nationality: 'Saudi' },
  { country: 'Singapore', nationality: 'Singaporean' },
  { country: 'South Africa', nationality: 'South African' },
  { country: 'South Korea', nationality: 'South Korean' },
  { country: 'Spain', nationality: 'Spanish' },
  { country: 'Sri Lanka', nationality: 'Sri Lankan' },
  { country: 'Sweden', nationality: 'Swedish' },
  { country: 'Switzerland', nationality: 'Swiss' },
  { country: 'Taiwan', nationality: 'Taiwanese' },
  { country: 'Thailand', nationality: 'Thai' },
  { country: 'Turkey', nationality: 'Turkish' },
  { country: 'United Arab Emirates', nationality: 'Emirati' },
  { country: 'United Kingdom', nationality: 'British' },
  { country: 'United States', nationality: 'American' },
  { country: 'Vietnam', nationality: 'Vietnamese' },
];
